export const CRM_PAGES = [
  { id: "admin-crm-dashboard", path: "crm/admin/dashboard", name: "Admin Dashboard", category: "admin-crm" },
  { id: "admin-crm-lead-overview", path: "crm/admin/lead-overview", name: "Lead Overview", category: "admin-crm" },
  { id: "admin-crm-all-leads", path: "crm/admin/all-leads", name: "All Leads", category: "admin-crm" },
  { id: "admin-crm-add-lead", path: "crm/admin/add-lead", name: "Add Lead", category: "admin-crm" },
  { id: "admin-crm-lead-sources", path: "crm/admin/lead-sources", name: "Lead Sources", category: "admin-crm" },
  { id: "admin-crm-lead-types", path: "crm/admin/lead-types", name: "Lead Types", category: "admin-crm" },
  { id: "admin-crm-import-export-leads", path: "crm/admin/import-export-leads", name: "Import & Export Leads", category: "admin-crm" },
  { id: "admin-crm-call-overview", path: "crm/admin/call-overview", name: "Call Overview", category: "admin-crm" },
  { id: "admin-crm-assigned-calls", path: "crm/admin/assigned-calls", name: "Assigned Calls", category: "admin-crm" },
  { id: "admin-crm-todays-calls", path: "crm/admin/todays-calls", name: "Today's Calls", category: "admin-crm" },
  { id: "admin-crm-pending-calls", path: "crm/admin/pending-calls", name: "Pending Calls", category: "admin-crm" },
  { id: "admin-crm-scheduled-calls", path: "crm/admin/scheduled-calls", name: "Scheduled Calls", category: "admin-crm" },
  { id: "admin-crm-completed-calls", path: "crm/admin/completed-calls", name: "Completed Calls", category: "admin-crm" },
  { id: "admin-crm-converted-calls", path: "crm/admin/converted-calls", name: "Converted Calls", category: "admin-crm" },
  { id: "admin-crm-transferred-calls", path: "crm/admin/transferred-calls", name: "Transferred Calls", category: "admin-crm" },
  { id: "admin-crm-call-history", path: "crm/admin/call-history", name: "Call History", category: "admin-crm" },
  { id: "admin-crm-follow-ups", path: "crm/admin/follow-ups", name: "Follow-Up Center", category: "admin-crm" },
  { id: "admin-crm-assignments", path: "crm/admin/assignments", name: "Assignments Overview", category: "admin-crm" },
  { id: "admin-crm-assignment-bulk", path: "crm/admin/assignment-bulk", name: "Bulk Assignment", category: "admin-crm" },
  { id: "admin-crm-assignment-history", path: "crm/admin/assignment-history", name: "Assignment History", category: "admin-crm" },
  { id: "admin-crm-workload", path: "crm/admin/workload", name: "Workload Distribution", category: "admin-crm" },
  { id: "marketing-overview", path: "crm/marketing/overview", name: "Marketing Overview", category: "admin-crm" },
  { id: "marketing-follow-ups", path: "crm/marketing/follow-ups", name: "Marketing Follow-Ups", category: "admin-crm" },
  { id: "visit-management", path: "crm/marketing/visits", name: "Visit Management", category: "admin-crm" },
  { id: "marketing-activity-history", path: "crm/marketing/activities", name: "Marketing Activity History", category: "admin-crm" },
  { id: "marketing-converted-leads", path: "crm/marketing/converted-leads", name: "Marketing Converted Leads", category: "admin-crm" },
  { id: "admin-crm-team-overview", path: "crm/admin/team", name: "Team Overview", category: "admin-crm" },
  { id: "admin-crm-users", path: "crm/admin/users", name: "Team Users", category: "admin-crm" },
  { id: "admin-crm-add-user", path: "crm/admin/add-user", name: "Add Team User", category: "admin-crm" },
  { id: "admin-crm-user-types", path: "crm/admin/user-type", name: "User Types", category: "admin-crm" },
  { id: "admin-crm-reports-overview", path: "crm/reports/overview", name: "Reports Overview", category: "admin-crm" },
  { id: "admin-crm-reports-leads", path: "crm/reports/leads", name: "Lead Reports", category: "admin-crm" },
  { id: "admin-crm-reports-calls", path: "crm/reports/calls", name: "Call Reports", category: "admin-crm" },
  { id: "admin-crm-reports-visits", path: "crm/reports/visits", name: "Visit Reports", category: "admin-crm" },
  { id: "admin-crm-reports-follow-ups", path: "crm/reports/follow-ups", name: "Follow-Up Reports", category: "admin-crm" },
  { id: "admin-crm-reports-team-performance", path: "crm/reports/team-performance", name: "Team Performance Reports", category: "admin-crm" },
  { id: "admin-crm-reports-conversion-funnel", path: "crm/reports/conversion-funnel", name: "Conversion Funnel Reports", category: "admin-crm" },
  { id: "admin-crm-reports-user-activity", path: "crm/reports/user-activity", name: "User Activity Reports", category: "admin-crm" },
];

// Legacy URLs use the same permission as their canonical page.
const CRM_PERMISSION_ALIASES = {
  "/ciisuser/crm": "/ciisUser/crm/admin/dashboard",
  "/ciisuser/crm/admin": "/ciisUser/crm/admin/dashboard",
  "/ciisuser/crm/leads": "/ciisUser/crm/admin/all-leads",
  "/ciisuser/crm/marketing": "/ciisUser/crm/marketing/overview",
  "/ciisuser/crm/followups": "/ciisUser/crm/admin/follow-ups",
  "/ciisuser/crm/leads/all": "/ciisUser/crm/admin/all-leads",
  "/ciisuser/crm/all-leads": "/ciisUser/crm/admin/all-leads",
  "/ciisuser/crm/lead-overview": "/ciisUser/crm/admin/lead-overview",
  "/ciisuser/crm/leads/overview": "/ciisUser/crm/admin/lead-overview",
  "/ciisuser/crm/leads/import": "/ciisUser/crm/admin/import-export-leads",
  "/ciisuser/crm/import-leads": "/ciisUser/crm/admin/import-export-leads",
  "/ciisuser/crm/leads/export": "/ciisUser/crm/admin/import-export-leads",
  "/ciisuser/crm/leads/sources": "/ciisUser/crm/admin/lead-sources",
  "/ciisuser/crm/lead-sources": "/ciisUser/crm/admin/lead-sources",
  "/ciisuser/crm/leads/add": "/ciisUser/crm/admin/add-lead",
  "/ciisuser/crm/add-lead": "/ciisUser/crm/admin/add-lead",
  "/ciisuser/crm/call-overview": "/ciisUser/crm/admin/call-overview",
  "/ciisuser/crm/calls/overview": "/ciisUser/crm/admin/call-overview",
  "/ciisuser/crm/calls/assigned": "/ciisUser/crm/admin/assigned-calls",
  "/ciisuser/crm/todays-calls": "/ciisUser/crm/admin/todays-calls",
  "/ciisuser/crm/calls/today": "/ciisUser/crm/admin/todays-calls",
  "/ciisuser/crm/pending-calls": "/ciisUser/crm/admin/pending-calls",
  "/ciisuser/crm/calls/pending": "/ciisUser/crm/admin/pending-calls",
  "/ciisuser/crm/scheduled-calls": "/ciisUser/crm/admin/scheduled-calls",
  "/ciisuser/crm/calls/scheduled": "/ciisUser/crm/admin/scheduled-calls",
  "/ciisuser/crm/completed-calls": "/ciisUser/crm/admin/completed-calls",
  "/ciisuser/crm/calls/completed": "/ciisUser/crm/admin/completed-calls",
  "/ciisuser/crm/converted-calls": "/ciisUser/crm/admin/converted-calls",
  "/ciisuser/crm/calls/converted": "/ciisUser/crm/admin/converted-calls",
  "/ciisuser/crm/transferred-calls": "/ciisUser/crm/admin/transferred-calls",
  "/ciisuser/crm/calls/transferred": "/ciisUser/crm/admin/transferred-calls",
  "/ciisuser/crm/call-history": "/ciisUser/crm/admin/call-history",
  "/ciisuser/crm/calls/history": "/ciisUser/crm/admin/call-history",
  "/ciisuser/crm/follow-ups": "/ciisUser/crm/admin/follow-ups",
  "/ciisuser/crm/assignments": "/ciisUser/crm/admin/assignments",
  "/ciisuser/crm/assignment-bulk": "/ciisUser/crm/admin/assignment-bulk",
  "/ciisuser/crm/assignment-history": "/ciisUser/crm/admin/assignment-history",
  "/ciisuser/crm/workload": "/ciisUser/crm/admin/workload",
  "/ciisuser/crm/calls": "/ciisUser/crm/admin/call-overview",
  "/ciisuser/crm/team": "/ciisUser/crm/admin/team",
  "/ciisuser/crm/users": "/ciisUser/crm/admin/users",
  "/ciisuser/crm/add-user": "/ciisUser/crm/admin/add-user",
  "/ciisuser/crm/user-type": "/ciisUser/crm/admin/user-type",
  "/ciisuser/crm/user-types": "/ciisUser/crm/admin/user-type",
  "/ciisuser/crm/reports/team": "/ciisUser/crm/reports/team-performance",
  "/ciisuser/crm/reports/funnel": "/ciisUser/crm/reports/conversion-funnel",
  "/ciisuser/crm/reports": "/ciisUser/crm/reports/overview",
  "/ciisuser/telecaller": "/ciisUser/telecaller/dashboard"
};

export const resolveCrmPermissionPath = path => CRM_PERMISSION_ALIASES[String(path).toLowerCase().replace(/\/+$/, "")] || path;
