export const websiteAppScreenMap = [
  {
    section: 'Public And Auth',
    routes: [
      {webUrl: '/', webPage: 'Home', appScreen: 'Home', status: 'available'},
      {webUrl: '/about', webPage: 'About Us', appScreen: 'Home', status: 'partial'},
      {webUrl: '/contact', webPage: 'Contact Us', appScreen: 'Contact Support', status: 'partial'},
      {webUrl: '/privacy-policy', webPage: 'Privacy Policy', appScreen: null, status: 'missing'},
      {webUrl: '/SuperAdminLogin', webPage: 'Super Admin Login', appScreen: 'SuperAdminLogin', status: 'available'},
      {webUrl: '/company/:companyCode/login', webPage: 'Company Login', appScreen: 'CompanyLogin', status: 'available'},
      {webUrl: '/RegisterCompany', webPage: 'Register Company', appScreen: 'RegisterCompany', status: 'available'},
    ],
  },
  {
    section: 'Super Admin',
    routes: [
      {webUrl: '/Ciis-network/company-details', webPage: 'Company Details', appScreen: 'Company Details', status: 'available'},
      {webUrl: '/Ciis-network/all-company', webPage: 'All Company', appScreen: 'All Company', status: 'available'},
      {webUrl: '/Ciis-network/CompanyManagement', webPage: 'Company Management', appScreen: 'Company Management', status: 'available'},
      {webUrl: '/Ciis-network/department', webPage: 'Department Management', appScreen: 'Department', status: 'available'},
      {webUrl: '/Ciis-network/department/branch/:branchId', webPage: 'Branch Departments', appScreen: 'Department', status: 'partial'},
      {webUrl: '/Ciis-network/JobRoleManagement', webPage: 'Job Role Management', appScreen: 'Job Roles', status: 'available'},
      {webUrl: '/Ciis-network/create-user', webPage: 'Create User', appScreen: 'Create User', status: 'available'},
      {webUrl: '/Ciis-network/company-assets', webPage: 'Company Assets', appScreen: 'Assets Management', status: 'available'},
      {webUrl: '/Ciis-network/company-assets/branch/:branchId', webPage: 'Branch Company Assets', appScreen: 'Assets Management', status: 'partial'},
      {webUrl: '/Ciis-network/SidebarManagement', webPage: 'Sidebar Management', appScreen: 'Sidebar Management', status: 'available'},
      {webUrl: '/Ciis-network/plans', webPage: 'Plans', appScreen: 'Plans', status: 'available'},
      {webUrl: '/Ciis-network/holiday', webPage: 'Holidays', appScreen: 'Holiday', status: 'available'},
      {webUrl: '/Ciis-network/branch', webPage: 'Branch Management', appScreen: 'Manage Branches', status: 'available'},
      {webUrl: '/Ciis-network/support-operations', webPage: 'Support Operations', appScreen: 'Support Operations', status: 'available'},
    ],
  },
  {
    section: 'HR Admin And Employee',
    routes: [
      {webUrl: '/ciisUser/user-dashboard', webPage: 'User Dashboard', appScreen: 'Dashboard', status: 'available'},
      {webUrl: '/ciisUser/change-password', webPage: 'Change Password', appScreen: 'Change Password', status: 'available'},
      {webUrl: '/ciisUser/emp-details', webPage: 'Employee Details', appScreen: 'Employee Details', status: 'available'},
      {webUrl: '/ciisUser/emp-leaves', webPage: 'Employee Leaves', appScreen: 'Employee Leaves', status: 'available'},
      {webUrl: '/ciisUser/emp-assets', webPage: 'Employee Assets', appScreen: 'Employee Assets', status: 'available'},
      {webUrl: '/ciisUser/emp-attendance', webPage: 'Employee Attendance', appScreen: 'Employee Attendance', status: 'available'},
      {webUrl: '/ciisUser/emp-task-details', webPage: 'Task Details', appScreen: 'Company All Task', status: 'partial'},
      {webUrl: '/ciisUser/admin-task-create', webPage: 'Admin Task Create', appScreen: 'Admin Task Create', status: 'available'},
      {webUrl: '/ciisUser/manage-groups', webPage: 'Manage Groups', appScreen: 'Manage Groups', status: 'available'},
      {webUrl: '/ciisUser/admin-meeting', webPage: 'Admin Meeting', appScreen: 'Admin Meeting', status: 'available'},
      {webUrl: '/ciisUser/adminproject', webPage: 'Admin Project', appScreen: 'Admin Project', status: 'available'},
      {webUrl: '/ciisUser/company-all-task', webPage: 'Company All Task', appScreen: 'Company All Task', status: 'available'},
      {webUrl: '/ciisUser/company-all-task/tasks', webPage: 'Company Task List', appScreen: 'Company All Task', status: 'partial'},
      {webUrl: '/ciisUser/company-all-task/tasks/:userId', webPage: 'User Task List', appScreen: 'Company All Task', status: 'partial'},
      {webUrl: '/ciisUser/company-all-task/:userId/tasks', webPage: 'User Task List', appScreen: 'Company All Task', status: 'partial'},
      {webUrl: '/ciisUser/emp-client', webPage: 'Client Management', appScreen: 'Client', status: 'available'},
      {webUrl: '/ciisUser/alert', webPage: 'Alerts', appScreen: 'Alerts', status: 'available'},
      {webUrl: '/ciisUser/create-alert', webPage: 'Create Alert', appScreen: 'Create Alert', status: 'available'},
      {webUrl: '/ciisUser/attendance', webPage: 'Attendance', appScreen: 'Attendance', status: 'available'},
      {webUrl: '/ciisUser/my-assets', webPage: 'My Assets', appScreen: 'My Assets', status: 'available'},
      {webUrl: '/ciisUser/my-leaves', webPage: 'My Leaves', appScreen: 'My Leaves', status: 'available'},
      {webUrl: '/ciisUser/profile', webPage: 'Profile', appScreen: 'Profile', status: 'available'},
      {webUrl: '/ciisUser/user-profile', webPage: 'User Profile', appScreen: 'Employee Profile', status: 'partial'},
      {webUrl: '/ciisUser/project', webPage: 'Project', appScreen: 'Project', status: 'available'},
      {webUrl: '/ciisUser/task-management', webPage: 'Task Management', appScreen: 'Task Management', status: 'available'},
      {webUrl: '/ciisUser/employee-meeting', webPage: 'Employee Meeting', appScreen: 'Meeting', status: 'available'},
      {webUrl: '/ciisUser/client-meeting', webPage: 'Client Meeting', appScreen: 'Client Meeting', status: 'available'},
      {webUrl: '/ciisUser/create-user', webPage: 'Create User', appScreen: 'Create User', status: 'available'},
      {webUrl: '/ciisUser/SidebarManagement', webPage: 'Sidebar Management', appScreen: 'Sidebar Management', status: 'available'},
      {webUrl: '/ciisUser/chat', webPage: 'Chat', appScreen: 'Chat', status: 'available'},
      {webUrl: '/ciisUser/support-desk', webPage: 'Department Support Desk', appScreen: 'Support Desk', status: 'available'},
      {webUrl: '/ciisUser/support-operations', webPage: 'Support Operations', appScreen: 'Support Operations', status: 'available'},
      {webUrl: '/ciisUser/ClientDashboard', webPage: 'Redirect To Client Dashboard', appScreen: 'Dashboard', status: 'redirect/web-only'},
    ],
  },
  {
    section: 'Client',
    routes: [
      {webUrl: '/client', webPage: 'Client Dashboard', appScreen: 'Dashboard', status: 'available'},
      {webUrl: '/client/dashboard', webPage: 'Client Dashboard', appScreen: 'Dashboard', status: 'available'},
      {webUrl: '/client/payment', webPage: 'Client Payment', appScreen: 'Payment', status: 'available'},
      {webUrl: '/client/services-tasks', webPage: 'Services & Tasks', appScreen: 'Services & Tasks', status: 'available'},
      {webUrl: '/client/change-password', webPage: 'Change Password', appScreen: 'Change Password', status: 'available'},
      {webUrl: '/client/*', webPage: 'Unknown Client Route', appScreen: 'Dashboard', status: 'redirect/web-only'},
    ],
  },
];

export const missingMobileScreens = websiteAppScreenMap.flatMap(section =>
  section.routes
    .filter(route => route.status === 'missing')
    .map(route => ({...route, section: section.section})),
);
